# Generated by Django 5.1.3 on 2024-11-19 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinaterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('Phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Report', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemname', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendComplaintAndViewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Subject', models.CharField(blank=True, max_length=150, null=True)),
                ('Complaint', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('PhoneNo', models.BigIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('PhoneNo', models.BigIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewAdminReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Subject', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Description', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewVolunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('PhoneNo', models.BigIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('Phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VictimInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('Phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=30, null=True)),
                ('VOLUNTEERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disaster_management_app.volunteerstable')),
            ],
        ),
        migrations.CreateModel(
            name='RequestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=150, null=True)),
                ('RESOURCE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disaster_management_app.resourcetable')),
                ('VOLUNTEERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disaster_management_app.volunteerstable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Subject', models.CharField(blank=True, max_length=150, null=True)),
                ('Reply', models.CharField(blank=True, max_length=150, null=True)),
                ('VOLUNTEER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disaster_management_app.volunteerstable')),
            ],
        ),
    ]
