# Generated by Django 5.1.3 on 2024-11-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disaster_management_app', '0003_reportstable_delete_reporttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetable',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
