# Generated by Django 5.1.3 on 2024-12-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disaster_management_app', '0004_alter_resourcetable_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendComplaintAndViewReply',
        ),
        migrations.DeleteModel(
            name='UserModule',
        ),
        migrations.DeleteModel(
            name='ViewAdminReport',
        ),
        migrations.DeleteModel(
            name='ViewResource',
        ),
        migrations.DeleteModel(
            name='ViewVolunteers',
        ),
    ]
