# Generated by Django 5.1.3 on 2025-01-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disaster_management_app', '0005_delete_sendcomplaintandviewreply_delete_usermodule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatertable',
            name='Place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
